 EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      #InstanceType:
      #  Ref: InstanceType
      InstanceType: "t2.micro"
      #SecurityGroups:
      #- Ref: InstanceSecurityGroup
      #KeyName:
      #  Ref: KeyName
      ImageId:
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - Fn::FindInMap:
          - AWSInstanceType2Arch
          - Ref: InstanceType
          - Arch
